apiVersion: apps/v1
kind: Deployment
metadata:
  name: keep-api
  labels:
    app: keep-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: keep-api
  template:
    metadata:
      labels:
        app: keep-api
        service: keep-api
    spec:
      containers:
        - name: keep-api
          image: dracma.azurecr.io/keep-api:test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: keep-api
  labels:
    app: keep-api
    service: keep-api
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: keep-api
