apiVersion: v1
kind: Pod
metadata:
  name: keep-api
  labels:
    app: api
spec:
  containers:
    - name: keep-api
      image: dracma.azurecr.io/keep-api:test
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
